[package]
name = "murpad"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13" }
rodio = { version = "0.21" }
anyhow = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.46", features = ["full"] }
